# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package -DskipTests'
- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub'
    command: 'login'
- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub'
    repository: 'sdhingra13/azure_qedge'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
- task: CopyFiles@2
  inputs:
    Contents: 'docker-compose.yml'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'compose'
    publishLocation: 'Container'
